Add Reverse function
VRublevski/strings pull request #1
Opened 2020-12-17 11:58 UTC by VRublevski

2020-12-17 12:38 UTC, papahmsolo requested changes
Looks great Vlad!

Let's see how can we improve this:
- Always make sure you run linters, I bet running `golint` will give you some warnings
- I know it's task 1.1 for you, but let's try to think of this from the user's perspective, you're writing your code for them. Do they know what's task 1.1 about? Also, it's a good practice to give PR meaningful names.
- Last but not least, is your module about _students-lab_ or some string manipulations?

2020-12-17 12:38 UTC, papahmsolo commented on util/util.go
> +package util
See guidelines about package names: 
https://github.com/golang/go/wiki/CodeReviewComments#package-names
https://golang.org/doc/effective_go.html#package-names

2020-12-17 12:38 UTC, papahmsolo commented on util/util.go
> +//returns the reversed string
The comment looks good, I'd just add an extra space after the slashes, https://golang.org/doc/effective_go.html#commentary

2020-12-17 12:38 UTC, papahmsolo commented on util/util_test.go
> +func TestUtil(t *testing.T) {
Are we testing `util` or something concrete like a function?

2020-12-17 12:38 UTC, papahmsolo commented on util/util_test.go
> +		},
What about non-ASCII test cases? I know your solution won't fail for such cases, but if your implementation wasm say to convert to a slice of bytes, it might've easily failed and your tests won't show it. Worth adding some extra.

2020-12-17 18:19 UTC, VRublevski commented on util/util.go
> +package util
I think I has fixed that.

2020-12-17 18:20 UTC, VRublevski commented on util/util.go
> +//returns the reversed string
I added an extra space.

2020-12-17 18:21 UTC, VRublevski commented on util/util_test.go
> +func TestUtil(t *testing.T) {
I renamed it to reflect the function under test

2020-12-17 18:21 UTC, VRublevski commented on util/util_test.go
> +		},
I have added some non-asci test cases.

2020-12-21 08:00 UTC, papahmsolo requested changes
Looks great Vlad! Almost ready to merge

2020-12-21 08:19 UTC, VRublevski commented on strings/strings_test.go
> +		t.Run(tt.inp, func(t *testing.T) {
I thoughts that it's good idea to have information about a particular input that failed when running tests, that's why I used `t.Run()` .

2020-12-21 08:19 UTC, VRublevski commented on strings/strings_test.go
> +		},
I added test cases for that.

2020-12-21 09:00 UTC, papahmsolo commented on strings/strings_test.go
> +		t.Run(tt.inp, func(t *testing.T) {
@VRublevski you're absolutely right, it's always a good idea. You can print the input in the error message

2020-12-21 09:04 UTC, papahmsolo requested changes
Not a critical one, but still. it's a quite simple package and module, you may want to have all the `.go` files in the root. No need to keep them in a separate `strings` folder.

2020-12-21 09:06 UTC, papahmsolo commented on strings/strings_test.go
> +		t.Run(tt.inp, func(t *testing.T) {
`t.Errorf("Reverse(%q): got %s want %s", tt.inp, got, want)`

2020-12-21 09:08 UTC, papahmsolo commented on strings/strings_test.go
> +			t.Errorf("got %s want %s", got, want)
`%q` format helps you to see leading and trailing spaces in the string, e.g. " string "

2020-12-21 09:12 UTC, VRublevski commented on strings/strings_test.go
> +		t.Run(tt.inp, func(t *testing.T) {
@papahmsolo Exactly! That was a silly suggest by me.

2020-12-21 09:23 UTC, VRublevski commented on strings/strings_test.go
> +			t.Errorf("got %s want %s", got, want)
@papahmsolo  I've followed your advice.

2020-12-21 09:29 UTC, papahmsolo approved these changes
Looks good to me!

2020-12-21 09:29 UTC, merged